### ISSUE TITLE
"not fully initialized" feature or bug ?

### ISSUE THREAD

**Issue by danieagle** [jrcarter/PragmARC#16]
Hi! Carter! :-)

Very very Very Thanks for all your work in Pragmarc!!

When compiling ParagmArc I'm getting these warnings:

 pragmarc-matching-character_regular_expression.adb
pragmarc-matching-character_regular_expression.ads:31:04: warning: in instantiation at pragmarc-matching-regular_expression.adb:30 [-gnatwv]
pragmarc-matching-character_regular_expression.ads:31:04: warning: aggregate not fully initialized [-gnatwv]

This is a feature or bug ?
I'm using gnat-14 from Ubuntu-24.04.01 LTS

Thanks!

GrateFull,
God and Mary Bless you,
Dani.

**Comment by jrcarter** [comment]
The aggregate is for a record type. The code says that the default values are OK for all components. The record has 5 components; 3 have explicit default values and one is a vector, which has an implicit default value of empty. The remaining component is of generic formal type Item. For this instantiation, the actual type is Character. Character does not have a default value. The aggregate may thus leave that component with an invalid value.

Since the aggregate has Kind = Stop, no other components of the record will be used (Kind = Stop is a sentinel to indicate that the end of the pattern has been reached), so I don't care what value the other components have. There does not seem to be any reason to worry about this warning.

If you want to use -gnatwv and not get this message, you can give your version of the record a default for Value, such as Any_Item.
