### ISSUE TITLE
(Question) Is possible limit or specify a max binary length for unbounded_integer ?

### ISSUE THREAD

**Issue by danieagle** [jrcarter/PragmARC#3]
Hi!

Is possible limit or specify a max binary length for unbounded_integer ?
Reason: to added It in files (binary files with reasonable specific layout) 

Thanks!
[]'s Dani.

**Comment by jrcarter** [comment]
On 9/8/20 5:34 PM, Daniel Norte de Moraes wrote:
> Is possible limit or specify a max binary length for unbounded_integer ?
>
> Reason: to added It in files (binary files with reasonable specific layout)
>
That is not possible. Indeed, an important feature driving the design was that
the user need never have to think about how much memory a value was occupying,
or could occupy.

Note that recent versions of GNAT have the Ada 2X Big_Numbers pkgs, but I don't
think they have what you're looking for, either.

Behind the scenes, an Unbounded_Integer contains a vector, and behind the
scenes, that vector undoubtedly contains an access value, so writing an
Unbounded_Integer to a binary file probably won't give you what you want, even
if its max length was limited.

You could add a Max_Digits discriminant to type Unbounded_Integer, and run-time
tests to raise Constraint_Error if a value exceeds that value. It still wouldn't
write correctly to a binary file.

You could write the padded Image of the value as a constrained String subtype,
and convert it with Value after reading it. Using base 36 would keep the strings
as short as possible.

Or you could easily modify the pkg into Bounded_Integers by using a bounded
vector. Probably that would be the only change needed. That would give you what
you want, and write correctly to a binary file.

HTH

-- 
Jeff Carter
"What's the amount of the insult?"
Never Give a Sucker an Even Break
104

**Comment by danieagle** [comment]
Thanks ! :-)

I'll analyze and test the options. :-) thanks for yours hints.

Thanks!
Best Wishes, Dani.

**Comment by danieagle** [comment]
Hi!
Pleaase! :-)
You Can review pragmarc.generic_bonded_integer.ad{sb} ?
[https://github.com/danieagle/PragmARC/tree/bounded_integer](url)

this still bugging:
main issues:
'image' ignores the maxdigits
'to_bonded_integer'  when maxdigits >= 2 can create a arbitrary long digits beyond maxdigits limits

Thanks :-) in Avance.
Best wishes, 
dani.

**Comment by jrcarter** [comment]
On 9/9/20 9:55 AM, Daniel Norte de Moraes wrote:
>
> Hi!
> Pleaase! :-)
> You Can review pragmarc.generic_bonded_integer.ad{sb} ?
> https://github.com/danieagle/PragmARC/tree/bounded_integer <url>
>
> this still bugging:
> main issues:
> 'image' ignores the maxdigits
> 'to_bonded_integer' when maxdigits >= 2 can create a arbitrary long digits
> beyond maxdigits limits
>
Clearly your problem is because you think Maxdigits is a good name, rather than
Max_Digits :)

I'm not sure what you mean by these "issues". Numbers are stored in base Radix
(usually 2 ** 16 or 2 ** 32); your bound is the max number of digits in that
base. Any attempt to use more digits (in that base) will cause an exception.
Perhaps I misunderstood what you're trying to achieve.

The number of digits used to represent a value depend on the base used.
2#1_0000_0000# = 10#256# = 32#80#. The larger the base, the fewer the digits.
Values represented by 1 digit in base Radix may take multiple digits to
represent in the bases provided by Base_Number.

It doesn't make sense to use fewer than 3 for the max digits, as most things
that can be done with a smaller max can be done directly with a regular integer
type.

-- 
Jeff Carter
"What I wouldn't give for a large sock with horse manure in it."
Annie Hall
42

**Comment by danieagle** [comment]
Hi J.R.Carter !
Please(!) I need a new revision :-)
[https://github.com/danieagle/PragmARC/tree/bounded_integer](url)
Thanks!!

Well... 
I first used low numbers to understanding the concept of digits, its real significance.
after this, very low and very high numbers usually reveal bugs and thinks to be done better. :-)

Thanks for this excelente framework!! :-)

Best Wishes,
[]'s Dani.

**Comment by jrcarter** [comment]
On 9/15/20 2:47 PM, Daniel Norte de Moraes wrote:
> I first used low numbers to understanding the concept of digits, its real
> significance.
>
> after this, very low and very high numbers usually reveal bugs and thinks to
> be done better. :-)
>
That looks OK to me. Of course, in most cases you can store more bits than
Max_Binary_Digits. What you really need to do is calculate

2 ** Max_Binary_Digits -1

and check that absolute values  are <= that.

-- 
Jeff Carter
"That was the most fun I've ever had without laughing."
Annie Hall
43

**Comment by danieagle** [comment]
Hi! :-)

Pleeeaase review the PR [https://github.com/jrcarter/PragmARC/pull/4](url) ! :-)
this is the final version. 

Best Wishes,
Dani. :-)

**Comment by jrcarter** [comment]
On 9/16/20 7:35 PM, Daniel Norte de Moraes wrote:
> Please I need a review. I change the calculi for max_capacity e add a func
>
> to calcule max decimal digits :-)
>
AFAICT, you changed some names and added a function, but otherwise everything is
the same.

> I can added categorization in It ?

I'm not sure what you mean by this.

> if yes 1st) I will add categorization 2nd)I will create a pull request.
> if no : I will create a pull request.
>
This fulfills some specialized requirements you had, but does not appear to be a
generally useful component, so even if it didn't use Ada-12 features (not
allowed in the Ada-07 branch) i will not be adding it to the PragmARCs.

-- 
Jeff Carter
"I'll get broads up here like you wouldn't believe.
Swingers. Freaks. Nymphomaniacs. Dental hygienists."
Play It Again, Sam
125

**Comment by danieagle** [comment]
Hi! :-)

 By Categorization, I say add Pragma Pure, pragma preelaborable_initialization etc, 
But I gave up on that. I edited the issues messages to reflect this.
 Don't exist bug. I just used in eba.ads  a Value("") with more digits the the bonded length.
 Now I'm removing all categorations and removing all parts in Ada2012.
 Now I'm removing all files not directly relationed with bounded_integer. 

 :-)

 Just to known, what is the maximum Ada standard allowed in Ada-07?
Best wishes, Dani. :-)

**Comment by jrcarter** [comment]
On 9/17/20 5:21 PM, Daniel Norte de Moraes wrote:
> By Categorization, I say add Pragma Pure, pragma preelaborable_initialization etc,

Since this is your pkg, you can add anything you like.

> Just to known, what is the maximum Ada standard allowed in Ada-07?

That would be the version of the standard published in 2007, ISO/IEC 8652:2007.

-- 
Jeff Carter
"I'll get broads up here like you wouldn't believe.
Swingers. Freaks. Nymphomaniacs. Dental hygienists."
Play It Again, Sam
125
