### ISSUE TITLE
(WhishList) update Threefish* to Pure and  Preelaborate. Very Very Very Thanks!

### ISSUE THREAD

**Issue by danieagle** [jrcarter/PragmARC#8]
Hi! 

 I updated Threefish packages to Pure and Preelaborate.

The main changes are in PramARC.Encryption.Treefish.adb.
 I replaced Ada.Unchecked_Conversion package + 2 function generic instantiations + 2 function calls 
with just a 2 or 3 normal variable assignment.

 Can you see and test it? [branch](https://github.com/danieagle/PragmARC/tree/preelaborate_or_pure)

 tf_test, tf_test_512 and tf_test_1024 from [Encryption-utilities](https://github.com/jrcarter/Encryption-utilities) worked for me.

I need this modification to use PragmArc Threefish on some
 systems I'm working on. Thank you very much!!

tested system: i7 + Linux Ubuntu AMD64 22.04.1 LTS + gnat-12 + gprbuild 2021.0.0.0778b109

Best Whishes,
GrateFull, Dani.

**Comment by jrcarter** [comment]
Using `Ada.Unchecked_Conversion` puts a big red flag at the top of the file that something unusual is happening. I'd need a good reason to take that away. What can you tell me about the systems you're working on and why they need these changes? That would help me decide if I want to make such a change. Are you actually using these conversion functions? The basic Threefish functionality doesn't need them.

In the meantime, this is released under the BSD 3-clause license, so you're free to make use of your modified version.

These aspects apply to the entire pkg, so they usually only appear on the spec.

When using an address overlay, it's usually a good idea to also use Import and Convention Ada. Using the Address aspect rather than the `for X'Address use` form is also probably a good idea.

I don't see why you're making a copy of the overlaid value. That should not be necessary.

**Comment by danieagle** [comment]
Hi!

Very Very Very Thanks!

> Using `Ada.Unchecked_Conversion` puts a big red flag at the top of the file that something unusual is happening. I'd need a good reason to take that away. What can you tell me about the systems you're working on and why they need these changes? That would help me decide if I want to make such a change. Are you actually using these conversion functions? The basic Threefish functionality doesn't need them.

We are creating a framework for digital currencies. if it works out, the libs 
and tools used will have great visibility to other developers and programmers
using our framework. This currency framework will be licensed as a public domain (Unlicence).

> These aspects apply to the entire pkg, so they usually only appear on the spec.

Great! I didn't know, living and learning, thank you! Programming in Ada is always a delight

> When using an address overlay, it's usually a good idea to also use Import and Convention Ada. Using the Address aspect rather than the `for X'Address use` form is also probably a good idea.

I'll change it. Thanks.

> 
> I don't see why you're making a copy of the overlaid value. That should not be necessary.

Force of habit, to not change the original variable, but this time it's okay to change
the original variable, and the variable is copied during return. Thank you so much! I hadn't noticed before.

 PramARC.Encryption.Treefish.adb can be preelaborate, it is more safe than pure.

I didn't say before, but maybe by replacing 1 function call with a simple view conversion per function, in addition to removing 1 package and 2 instantiations, threefish got a little faster and as threefish pervade may network part this is a greate speed up by my system. ah! and with the suggested changes it will be even faster. Very Very Very Thanks!

Best Wishes,
GrateFull, Dani.

**Comment by jrcarter** [comment]
That doesn't tell me why you need them to be Pure/Preelaborate.

Since these conversion functions are not used by Threefish, I presume, since you say that your changes make things a little faster, that you are using them. Note that instantiation has no run-time impact. Using an overlay probably eliminates a copy.

**Comment by danieagle** [comment]
> That doesn't tell me why you need them to be Pure/Preelaborate.

Because otherwise Threefish will directly or indirectly cascade down _ALL_ :-D  packages in our digital currency framework to
 'none' categorization (without 'with pure' and without 'with preelaborate')
 and the only thing preventing the pragmarc-encryption-threefish-block_* packages from upgrading 
 to pure (or at least preelaborate) is pragmarc-encryption-threefish being 'nothing' categorization.

Funny fact: the original reason for contributing and creating Threefish with 1024 and 512bit blocks was also to use it in our digital currency  framework.

> Since these conversion functions are not used by Threefish, I presume, since you say that your changes make things a little faster, that you are using them.

I created a _minimal_ test case for learning and benckmark threefish, not yet the integration in our currency framework.

The actual convertion is more for speedy.  The use of Ada.Unchecked_Conversion is ok, too.

> Note that instantiation has no run-time impact. 

Great! I didn't know! Living and learning!

Best Wishes,
GreateFull,
Dani.

p.s.:  I'm  asking some things to in the Ada Newsgroup,
to determine if pragmarc-encryption-threefish-block_* packages can be Pure, too.

**Comment by jrcarter** [comment]
Yes, but why do you need your digital-currency framework to be preelaborable?

Looking more closely at [ARM 13.11.2](http://www.ada-auth.org/standards/rm12_w_tc1/html/RM-13-11-2.html) I see that `Ada.Unchecked_Deallocation` is marked as preelaborable, so I will mark `PragmARC.Encryption.Threefish` and its children the same. One would think it could be Pure, since typically it does nothing, but so it goes.

I will close this issue if that is satisfactory to you.

**Comment by danieagle** [comment]
Hi! and Thanks!

As far as I know [Ada.Unchecked_Conversion](http://www.ada-auth.org/standards/12aarm/html/AA-13-9.html) is Ada Pure. :-) 

I believe that all Threefish packs can be Ada Pure.

Very GrateFull, Dani.

**Comment by jrcarter** [comment]
I got the wrong `Unchecked_`. What a stupid mistake. OK, I'll make them Pure.

**Comment by danieagle** [comment]
Hi Carter! VeryVeryVery(!!) Thanks!!!!!

I'm closing this issue:-)

Very Very Very Gratefull,
Very Very Very Best Whishes,
Dani.
